# Additional CronJob examples for different scenarios

# Daily document processing at 6 AM
apiVersion: batch/v1
kind: CronJob
metadata:
  name: document-notification-daily
  namespace: default
spec:
  schedule: "0 6 * * *"  # Daily at 6 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: document-notification-service
            component: daily-process
        spec:
          restartPolicy: OnFailure
          containers:
          - name: document-notification
            image: document-notification-service:latest
            args: ["process", "--force"]
            envFrom:
            - configMapRef:
                name: document-notification-env
            - secretRef:
                name: document-notification-secrets
            volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: logs-volume
              mountPath: /app/logs
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: config-volume
            configMap:
              name: document-notification-config
          - name: logs-volume
            emptyDir: {}
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3

---
# Retry failed documents - daily at 8 PM
apiVersion: batch/v1
kind: CronJob
metadata:
  name: document-notification-retry
  namespace: default
spec:
  schedule: "0 20 * * *"  # Daily at 8 PM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: document-notification-service
            component: retry
        spec:
          restartPolicy: OnFailure
          containers:
          - name: document-notification
            image: document-notification-service:latest
            args: ["retry", "--all"]
            envFrom:
            - configMapRef:
                name: document-notification-env
            - secretRef:
                name: document-notification-secrets
            volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: logs-volume
              mountPath: /app/logs
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: config-volume
            configMap:
              name: document-notification-config
          - name: logs-volume
            emptyDir: {}
  successfulJobsHistoryLimit: 7
  failedJobsHistoryLimit: 3

---
# Weekly status check - every Sunday at 9 AM
apiVersion: batch/v1
kind: CronJob
metadata:
  name: document-notification-status
  namespace: default
spec:
  schedule: "0 9 * * 0"  # Every Sunday at 9 AM
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: document-notification-service
            component: status
        spec:
          restartPolicy: OnFailure
          containers:
          - name: document-notification
            image: document-notification-service:latest
            args: ["status", "--limit", "50"]
            envFrom:
            - configMapRef:
                name: document-notification-env
            - secretRef:
                name: document-notification-secrets
            volumeMounts:
            - name: config-volume
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            resources:
              requests:
                memory: "256Mi"
                cpu: "250m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          volumes:
          - name: config-volume
            configMap:
              name: document-notification-config
  successfulJobsHistoryLimit: 4
  failedJobsHistoryLimit: 2