apiVersion: v1
kind: Secret
metadata:
  name: document-notification-secrets
  namespace: default
type: Opaque
data:
  # Database Configuration (base64 encoded)
  # Default: Server=.;Database=DocumentNotificationDB;Integrated Security=true;TrustServerCertificate=true;
  Database__ConnectionString: U2VydmVyPS47RGF0YWJhc2U9RG9jdW1lbnROb3RpZmljYXRpb25EQjtJbnRlZ3JhdGVkIFNlY3VyaXR5PXRydWU7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT10cnVlOw==
  
  # DSX Service Authentication (base64 encoded)
  # Default username: user
  DSXService__Username: dXNlcg==
  # Default password: pass
  DSXService__Password: cGFzcw==
  
  # RabbitMQ Authentication (base64 encoded)
  # Default username: ce
  RabbitMQ__UserName: Y2U=
  # Default password: ce
  RabbitMQ__Password: Y2U=
  
  # Email Authentication (base64 encoded, empty by default)
  Email__UserName: ""
  Email__Password: ""
---
# Alternative Secret configuration using stringData for easier management
# This version shows the actual values for reference - use this during deployment
apiVersion: v1
kind: Secret
metadata:
  name: document-notification-secrets-template
  namespace: default
type: Opaque
stringData:
  # Database Configuration
  Database__ConnectionString: "Server=sql-server;Database=DocumentNotificationDB;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;"
  
  # DSX Service Authentication
  DSXService__Username: "your-dsx-username"
  DSXService__Password: "your-dsx-password"
  
  # RabbitMQ Authentication  
  RabbitMQ__UserName: "your-rabbitmq-username"
  RabbitMQ__Password: "your-rabbitmq-password"
  
  # Email Authentication (if required)
  Email__UserName: "your-email-username"
  Email__Password: "your-email-password"